### PR TITLE
fix: ensure deprecated flags are correctly hidden

### LINKED ISSUE #1971: bug: dev and deprecated flags shown by when running `conduit help`
### Feature description

The --dev flags (used for profiling) should be hidden when `conduit help` is run. This is how we had before v0.12.2 when we unintentionally made them visible by default as part of some other CLI changes.

### PR DESCRIPTION
**Pull request by raulb**
### Description

Fixes #1971 

The `Flags()` method on `entrypoint.go` is used in different places, and this pull-requests ensure that both the usage by this method and when using via the main Conduit CLI is correctly set. 

Added unit tests to avoid regressions.

**Before**

```
Conduit CLI is a command-line that helps you interact with and manage Conduit.

Usage:
  conduit [flags]
  conduit [command]

Pipelines
  pipelines   Initialize and manage pipelines

Additional Commands:
  help        Help about any command
  init        Initialize Conduit with a configuration file and directories.

Flags:
      --api.enabled                                            enable HTTP and gRPC API (default true)
      --connectors.path string                                 path to standalone connectors' directory (default "/Users/rb/code/conduitio/conduit/connectors")
      --db.badger.path string                                  path to badger DB (default "/Users/rb/code/conduitio/conduit/conduit.db")
      --db.postgres.connection-string string                   postgres connection string, may be a database URL or in PostgreSQL keyword/value format
      --db.postgres.table string                               postgres table in which to store data (will be created if it does not exist) (default "conduit_kv_store")
      --db.sqlite.path string                                  path to sqlite3 DB (default "/Users/rb/code/conduitio/conduit/conduit.db")
      --db.sqlite.table string                                 sqlite3 table in which to store data (will be created if it does not exist) (default "conduit_kv_store")
      --db.type string                                         database type; accepts badger,postgres,inmemory,sqlite (default "badger")
      --dev                                                    used together with the dev flag it shows dev flags
      --dev.blockprofile string                                write block profile to file
      --dev.cpuprofile string                                  write cpu profile to file
      --dev.memprofile string                                  write memory profile to file
      --grpc.address string                                    address for serving the gRPC API (default ":8084")
  -h, --help                                                   help for conduit
      --http.address string                                    address for serving the HTTP API (default ":8080")
      --log.format string                                      sets the format of the logging; accepts json, cli (default "cli")
      --log.level string                                       sets logging level; accepts debug, info, warn, error, trace (default "info")
      --pipelines.error-recovery.backoff-factor int            backoff factor applied to the last delay (default 2)
      --pipelines.error-recovery.max-delay duration            maximum delay before restart (default 10m0s)
      --pipelines.error-recovery.max-retries int               maximum number of retries (default -1)
      --pipelines.error-recovery.max-retries-window duration   amount of time running without any errors after which a pipeline is considered healthy (default 5m0s)
      --pipelines.error-recovery.min-delay duration            minimum delay before restart (default 1s)
      --pipelines.exit-on-degraded                             exit Conduit if a pipeline enters a degraded state
      --pipelines.exit-on-error exit-on-degraded               Deprecated: use exit-on-degraded instead.
                                                               exit Conduit if a pipeline experiences an error while running
      --pipelines.path string                                  path to the directory that has the yaml pipeline configuration files, or a single pipeline configuration file (default "/Users/rb/code/conduitio/conduit/pipelines")
      --preview.pipeline-arch-v2                               enables experimental pipeline architecture v2 (note that the new architecture currently supports only 1 source and 1 destination per pipeline)
      --processors.path string                                 path to standalone processors' directory (default "/Users/rb/code/conduitio/conduit/processors")
      --schema-registry.confluent.connection-string string     confluent schema registry connection string
      --schema-registry.type string                            schema registry type; accepts builtin,confluent (default "builtin")
  -v, --version                                                version for conduit

Use "conduit [command] --help" for more information about a command.
```

**After**

```
Conduit CLI is a command-line that helps you interact with and manage Conduit.

Usage:
  conduit [flags]
  conduit [command]

Pipelines
  pipelines   Initialize and manage pipelines

Additional Commands:
  help        Help about any command
  init        Initialize Conduit with a configuration file and directories.

Flags:
      --api.enabled                                            enable HTTP and gRPC API (default true)
      --connectors.path string                                 path to standalone connectors' directory (default "/Users/rb/code/conduitio/conduit/connectors")
      --db.badger.path string                                  path to badger DB (default "/Users/rb/code/conduitio/conduit/conduit.db")
      --db.postgres.connection-string string                   postgres connection string, may be a database URL or in PostgreSQL keyword/value format
      --db.postgres.table string                               postgres table in which to store data (will be created if it does not exist) (default "conduit_kv_store")
      --db.sqlite.path string                                  path to sqlite3 DB (default "/Users/rb/code/conduitio/conduit/conduit.db")
      --db.sqlite.table string                                 sqlite3 table in which to store data (will be created if it does not exist) (default "conduit_kv_store")
      --db.type string                                         database type; accepts badger,postgres,inmemory,sqlite (default "badger")
      --dev.blockprofileblockprofile string                    write block profile to file
      --dev.cpuprofile string                                  write cpu profile to file
      --dev.memprofile string                                  write memory profile to file
      --grpc.address string                                    address for serving the gRPC API (default ":8084")
  -h, --help                                                   help for conduit
      --http.address string                                    address for serving the HTTP API (default ":8080")
      --log.format string                                      sets the format of the logging; accepts json, cli (default "cli")
      --log.level string                                       sets logging level; accepts debug, info, warn, error, trace (default "info")
      --pipelines.error-recovery.backoff-factor int            backoff factor applied to the last delay (default 2)
      --pipelines.error-recovery.max-delay duration            maximum delay before restart (default 10m0s)
      --pipelines.error-recovery.max-retries int               maximum number of retries (default -1)
      --pipelines.error-recovery.max-retries-window duration   amount of time running without any errors after which a pipeline is considered healthy (default 5m0s)
      --pipelines.error-recovery.min-delay duration            minimum delay before restart (default 1s)
      --pipelines.exit-on-degraded                             exit Conduit if a pipeline enters a degraded state
      --pipelines.path string                                  path to the directory that has the yaml pipeline configuration files, or a single pipeline configuration file (default "/Users/rb/code/conduitio/conduit/pipelines")
      --preview.pipeline-arch-v2                               enables experimental pipeline architecture v2 (note that the new architecture currently supports only 1 source and 1 destination per pipeline)
      --processors.path string                                 path to standalone processors' directory (default "/Users/rb/code/conduitio/conduit/processors")
      --schema-registry.confluent.connection-string string     confluent schema registry connection string
      --schema-registry.type string                            schema registry type; accepts builtin,confluent (default "builtin")
  -v, --version                                                version for conduit

Use "conduit [command] --help" for more information about a command.
```

### Quick checks

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [x] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: pkg/conduit/entrypoint.go [hunk 1]
```diff
@@ -20,22 +20,32 @@ import (
...
+	FlagPipelinesExitOnError = "pipelines.exit-on-error"
 )
 
+// HiddenFlags is a map of flags that should not be shown in the help output.
+var HiddenFlags = map[string]bool{
+	FlagPipelinesExitOnError: true,
+	FlagDevCpuProfile:        true,
+	FlagDevMemProfile:        true,
+	FlagDevBlockProfile:      true,
+}
```
Comment (hariso) [inline pkg/conduit/entrypoint.go:47]: Just to share a thought (I don't think we need to change anything now): this looks good to me, but what I liked about the previous version (where we checked for the `dev` prefix) is that it was a rule and not an enumeration. That way, if we ever add a new dev flag, it will automatically be excluded.

File: pkg/conduit/entryoint_test.go
Comment (hariso) [inline pkg/conduit/entryoint_test.go:1]: Typo in file name, entryoint vs entrypoint.

File: pkg/conduit/entrypoint.go (hunk 1 above)
Comment (raulb) [reply pkg/conduit/entrypoint.go:47]: You got a point. Will refactor.

File: pkg/conduit/entrypoint.go [hunk 2]
```diff
@@ -163,18 +173,21 @@ func Flags(cfg *Config) *flag.FlagSet {
 
 	flags.BoolVar(&cfg.Preview.PipelineArchV2, "preview.pipeline-arch-v2", cfg.Preview.PipelineArchV2, "enables experimental pipeline architecture v2 (note that the new architecture currently supports only 1 source and 1 destination per pipeline)")
 
-	// NB: flags with prefix dev.* are hidden from help output by default, they only show up using '-dev -help'
-	showDevHelp := flags.Bool("dev", false, "used together with the dev flag it shows dev flags")
```
Comment (hariso) [inline pkg/conduit/entrypoint.go:167]: Hmm, shouldn't we keep this? Or do you think we shouldn't provide an option to show these at all?

Comment (raulb) [reply pkg/conduit/entrypoint.go:167]: @hariso as far as I can tell, that flag wasn't really doing anything. Going to check with an old version of conduit to see if in some point it should have.

Comment (raulb) [reply pkg/conduit/entrypoint.go:167]: @hariso looks like what I was testing was another regression

```
go run ./cmd/conduit/main.go --dev --help
Usage of conduit:
  -dev.blockprofile string
    	write block profile to file
  -dev.cpuprofile string
    	write cpu profile to file
  -dev.memprofile string
    	write memory profile to file
```

That's not working on main now either. Will fix

Comment (raulb) [reply pkg/conduit/entrypoint.go:167]: As per standup, we decided to leave these visible.

**Review by hariso — APPROVED** [review]
