### PR TITLE
Track recovery attempts using leaky bucket

### LINKED ISSUE #1862: [Recovery] Add delay after which fail count is reset
### Feature description

As described in this [design document](https://github.com/ConduitIO/conduit/blob/main/docs/design-documents/20240812-recover-from-pipeline-errors.md), to control intermittent errors, the recovery mechanism will have a parameter named `HealthyAfter` that  

[This pull-request](https://github.com/ConduitIO/conduit/pull/1853) implemented the restart of a pipeline to be recovered, but it was considered tackling `HealthyAfter` separately considering it'd increase its scope notably.

## Some details

- The `backoff` will be reset only when a pipeline processes at least one record or runs without encountering an error for a predefined time frame.
- Each pipeline will control its own `HealthyAfter` duration https://github.com/ConduitIO/conduit/blob/raul/restart-with-recovery/pkg/lifecycle/service.go#L55.
- This will need to be updated once we have this delay in place https://github.com/ConduitIO/conduit/blob/raul/restart-with-recovery/pkg/lifecycle/service.go#L752-L756.

## Possible solution

Spawn a goroutine that resets the backoff after a certain time.

### PR DESCRIPTION
**Pull request by lovromazgon**
### Description

This PR implements tracking of recovery attempts using a [leaky bucket](https://en.wikipedia.org/wiki/Leaky_bucket). Once the bucket is full (i.e. we exceed the `MaxRetries` threshold) the pipeline is degraded instead of recovered.

Fixes #1862 

### Quick checks

- [X] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [x] I have written unit tests.
- [X] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

**Review by raulb — APPROVED** [review]

File: pkg/lifecycle/service.go [hunk 1]
```diff
@@ -220,7 +220,12 @@ func (s *Service) StartWithBackoff(ctx context.Context, rp *runnablePipeline) er
 		Int64(log.AttemptField, attempt).
 		Msg("restarting with backoff")
 
-	time.AfterFunc(duration+s.errRecoveryCfg.HealthyAfter, func() {
+	time.AfterFunc(duration+s.errRecoveryCfg.MaxRetriesWindow, func() {
+		s.logger.Info(ctx).
```
Comment (lovromazgon) [inline pkg/lifecycle/service.go:224]: Maybe this should be a debug log?

**Review by lovromazgon — COMMENTED** [review]
LGTM, I'd approve if I could, but I can't because I'm officially the author. Posted a nitpick, but that's about it 👍

File: pkg/lifecycle/service.go (hunk 1 above)
Comment (raulb) [reply pkg/lifecycle/service.go:224]: @lovromazgon I questioned myself about it too, so I'll change it to debug.
