### PR TITLE
[UI] Add synchronous start/stop pipeline error notifications

### LINKED ISSUE #127: Bug: UI doesn't expose initial start/stop pipeline request errors
### Bug description

When starting/stopping a pipeline, we handle asynchronous polling errors, but we do not handle the errors from the initial requests to start and stop a pipeline. This means that we only expose errors when a pipeline successfully starts and then errors out, but not when a pipeline unsuccessfully starts. 

### Steps to reproduce

1. While using the UI
2. Force an error response from the `v1/pipelines/:id/start` endpoint
3. Notice no error message is shown
4. Compare this to a success response from `v1/pipelines/:id/start` that then polls an error from the `v1/pipelines/:id` endpoint, where an error is shown. 

### Version

v0.1.0

### PR DESCRIPTION
**Pull request by jmar910**
### Description
We wrote an error system around handling asynchronous pipeline errors, but it doesnt handle synchronous pipeline errors 😅  

This PR addresses that

Fixes #127 

### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [x] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: ui/app/controllers/pipeline.js [hunk 1]
```diff
@@ -25,6 +31,12 @@ export default class PipelineController extends Controller {
 
   @action
   async stopPipeline(pipeline) {
+    try {
+      await pipeline.startPipeline();
```
Comment (jayjayjpg) [inline ui/app/controllers/pipeline.js:35]: Is there also a `stopPipeline` method that could be used here, instead of `startPipeline`?

File: ui/app/controllers/pipeline.js [hunk 2]
```diff
@@ -25,6 +31,12 @@ export default class PipelineController extends Controller {
...
+    } catch (error) {
+      this._handleStartStopPipelineError(error);
+      return;
+    }
     await pipeline.stopPipeline();
```
Comment (jayjayjpg) [inline ui/app/controllers/pipeline.js:40]: Would this line move into the `try / catch` block or should this rather be run on its own?

File: ui/tests/acceptance/pipeline/index-test.js [hunk 3]
```diff
@@ -166,6 +167,35 @@ module('Acceptance | pipeline/index', function (hooks) {
...
+      });
+
+      await visit(`/pipelines/${pipeline.id}`);
+
+      await click(page.pipelineStatusButton);
+
+      await click(page.pipelineStatusStart);
+    });
+
+    test('it displays an error notification', function (assert) {
```
Comment (jayjayjpg) [inline ui/tests/acceptance/pipeline/index-test.js:194]: Nice test case! :sparkles:

File: ui/app/controllers/pipeline.js [hunk 4]
```diff
@@ -24,8 +30,14 @@ export default class PipelineController extends Controller {
   }
 
   @action
+  @waitFor
   async stopPipeline(pipeline) {
-    await pipeline.stopPipeline();
+    try {
+      await pipeline.stopPipeline();
```
Comment (jayjayjpg) [inline ui/app/controllers/pipeline.js:36]: Nice! :sparkles:

File: ui/tests/acceptance/pipeline/index-test.js [hunk 5]
```diff
@@ -166,6 +168,69 @@ module('Acceptance | pipeline/index', function (hooks) {
...
+      assert.dom(page.errorTitle).containsText('failed to start pipeline');
+    });
+  });
+
+  module('stopping a pipeline that synchronously errors out', function (hooks) {
+    hooks.beforeEach(async function () {
+      this.server.logging = true;
```
Comment (jayjayjpg) [inline ui/tests/acceptance/pipeline/index-test.js:202]: I think this one can go, or what are your thoughts?

File: ui/tests/acceptance/pipeline/index-test.js [hunk 6]
```diff
@@ -166,6 +168,69 @@ module('Acceptance | pipeline/index', function (hooks) {
...
+      });
+
+      await visit(`/pipelines/${pipeline.id}`);
+
+      await click(page.pipelineStatusButton);
+
+      await click(page.pipelineStatusStop);
+    });
+
+    test('it displays an error notification', function (assert) {
```
Comment (jayjayjpg) [inline ui/tests/acceptance/pipeline/index-test.js:229]: Nice testing addition! :sparkles:

**Review by jayjayjpg — APPROVED** [review]
This reads great and nice test coverage! :sparkles:
