### PR TITLE
Close WebSocket connections when shutting down

### LINKED ISSUE #747: Conduit cannot shutdown gracefully with open inspector sessions
### Bug description

https://github.com/ConduitIO/conduit/pull/718#discussion_r1028081348

### Steps to reproduce

1. Start Conduit with a pipeline
2. Inspect a connector
3. Shut down Conduit gracefully (e.g. Ctrl+C or `kill -2`)

**Expected behavior**:
Conduit is shut down.

**Actual behavior**:
Conduit is not shut down.

### Version

TBD

### PR DESCRIPTION
**Pull request by hariso**
### Description

Fixes #747.

We generally have 2 options for fixing this: close the inspector session or close the WebSocket connection (which in the end closes the inspector as well). The second one is more generic and reusable. WebSocket connections are generally long-lived and we should be closing them when shutting (as opposed to HTTP API calls, which are not expected to be long-living so waiting for them to be done when shutting down makes sense).

### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [x] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: pkg/foundation/grpcutil/websocket.go [hunk 1]
```diff
@@ -82,7 +84,10 @@ func newWebSocketProxy(handler http.Handler, logger log.CtxLogger) *webSocketPro
 		pongWait:   defaultPongWait,
 		pingPeriod: (defaultPongWait * 9) / 10,
 	}
-
+	go func() {
+		<-ctx.Done()
+		proxy.done <- struct{}{}
+	}()
```
Comment (lovromazgon) [inline pkg/foundation/grpcutil/websocket.go:90]: Doing it this way we will only notify one websocket connection that Conduit is shutting down. We need to close the channel to notify all of them.

And while we're at it, we could simply assign `ctx.Done()` to `done`, it's already a channel that will be closed when the context is closed. We don't need this goroutine then.

File: pkg/foundation/grpcutil/websocket.go [hunk 2]
```diff
@@ -112,6 +117,10 @@ func (p *webSocketProxy) proxy(w http.ResponseWriter, r *http.Request) {
 	ctx, cancelFn := context.WithCancel(r.Context())
 	defer cancelFn()
 	r = r.WithContext(ctx)
+	go func() {
+		<-p.done
```
Comment (lovromazgon) [inline pkg/foundation/grpcutil/websocket.go:121]: This goroutine will linger until Conduit is stopped, it would be nicer if we would also listen to `ctx.Done()` (the request context). To make this easier, we can use the utility methods in package `cchan`.

**Review by lovromazgon — COMMENTED** [review]
I think this makes sense, just a few comments on simplifying the solution 🙂

File: pkg/foundation/grpcutil/websocket.go (hunk 1 above)
Comment (hariso) [reply pkg/foundation/grpcutil/websocket.go:90]: Good callout!

**Review by lovromazgon — COMMENTED** [review]
First of all - the approach works and I like it, simple and effective. Good job 👍

You made me aware of the logs (you can blame yourself for this 😄). Since we're probably not going to touch this code for some time, I think it would be nice to clean up log messages and make sure we don't give the impression that there was an error if everything was fine.

Here's what I see in the logs when the UI navigates away from a pipeline page and closes two inspector sessions (one for the source, one for the destination):
```
2023-02-23T16:53:11+00:00 WRN read error error="websocket: close 1005 (no status)" component=grpcutil.webSocketProxy stack=null
2023-02-23T16:53:11+00:00 ERR error processing HTTP request error="rpc error: code = Canceled desc = context canceled" http_endpoint="GET /v1/connectors/file-to-file:example.in/inspect" request_id=4118a602-edc3-40a9-8db7-6c57397e5c26 stack=null
2023-02-23T16:53:11+00:00 WRN request context returned an error: context canceled component=grpcutil.webSocketProxy
2023-02-23T16:53:11+00:00 WRN [write] error writing websocket message error="websocket: close sent" component=grpcutil.webSocketProxy stack=null
2023-02-23T16:53:11+00:00 WRN read error error="websocket: close 1005 (no status)" component=grpcutil.webSocketProxy stack=null
2023-02-23T16:53:11+00:00 WRN request context returned an error: context canceled component=grpcutil.webSocketProxy
2023-02-23T16:53:11+00:00 INF context canceled: context canceled component=inspector.Session connector_id=file-to-file:example.in
2023-02-23T16:53:11+00:00 INF session removed component=inspector.Inspector connector_id=file-to-file:example.in inspector_session_id=b3df114b-a3ef-47a5-9c7f-58d5317b543b
2023-02-23T16:53:11+00:00 ERR error processing HTTP request error="rpc error: code = Canceled desc = context canceled" http_endpoint="GET /v1/connectors/file-to-file:example.out/inspect" request_id=d0195057-6f4d-4e7d-95c5-b28eac02124e stack=null
2023-02-23T16:53:11+00:00 WRN [write] error writing websocket message error="websocket: close sent" component=grpcutil.webSocketProxy stack=null
2023-02-23T16:53:11+00:00 INF context canceled: context canceled component=inspector.Session connector_id=file-to-file:example.out
2023-02-23T16:53:11+00:00 INF session removed component=inspector.Inspector connector_id=file-to-file:example.out inspector_session_id=de33b35c-ff9b-495c-a8c1-a8bd31c53540
```

That's quite a lot, especially when everything went fine and log level is set to INFO. It's important to note that no records were flowing through the pipeline at that point, which is strange, because the websocket write goroutine is hitting line 258, which would mean it's trying to write a message.

Ideally I'd expect to see a single log message saying that the inspector session was successfully stopped (one for each session).

When shutting down Conduit with open inspector sessions I see:
```
2023-02-23T16:56:46+00:00 WRN conduit is stopping, stand by for shutdown ...
2023-02-23T16:56:46+00:00 ERR error processing HTTP request error="rpc error: code = Canceled desc = context canceled" http_endpoint="GET /v1/connectors/file-to-file:example.in/inspect" request_id=ede336df-3033-4a06-8303-63833de30541 stack=null
2023-02-23T16:56:46+00:00 ERR error processing HTTP request error="rpc error: code = Canceled desc = context canceled" http_endpoint="GET /v1/connectors/file-to-file:example.out/inspect" request_id=2538421f-e444-429d-a623-58a066c81957 stack=null
2023-02-23T16:56:46+00:00 WRN read error error="read tcp [::1]:8080->[::1]:51974: use of closed network connection" component=grpcutil.webSocketProxy
2023-02-23T16:56:46+00:00 INF context canceled: context canceled component=inspector.Session connector_id=file-to-file:example.in
2023-02-23T16:56:46+00:00 INF session removed component=inspector.Inspector connector_id=file-to-file:example.in inspector_session_id=1f0260c0-f366-4ac8-8a9e-5f5dab618afe
2023-02-23T16:56:46+00:00 INF context canceled: context canceled component=inspector.Session connector_id=file-to-file:example.out
2023-02-23T16:56:46+00:00 WRN read error error="read tcp [::1]:8080->[::1]:51975: use of closed network connection" component=grpcutil.webSocketProxy
2023-02-23T16:56:46+00:00 INF session removed component=inspector.Inspector connector_id=file-to-file:example.out inspector_session_id=692ce6fc-a0d9-4fc9-9702-2e15488bfab1
```

I hope we can at least clean up the messages originating in this file and make sure that error logs are actually errors.

File: pkg/foundation/grpcutil/websocket.go [hunk 3]
```diff
@@ -114,12 +113,20 @@ func (p *webSocketProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
-		cancelFn()
+		// we're using ChanOut.Recv() so that the goroutine doesn't wait on
+		// the proxy to be done even when the request is done
+		_, ok, err := cchan.ChanOut[struct{}](p.done).Recv(ctx)
+		if err != nil {
+			p.logger.Warn(ctx).Msgf("request context returned an error: %v", err)
+		}
+		if ok {
+			p.logger.Info(ctx).Msg("shutting down")
+		}
```
[the remark this answers is not in the document]
Comment (hariso) [reply pkg/foundation/grpcutil/websocket.go:128]: I think you have a point about the "shutting down". For the warning above, it was because there's a possibility that `ctx.Err()` returns a `DeadlineExceeded`, which I believe is a bit unexpected. So I went the route of logging a bit more, to catch that as well.

**Comment by hariso** [comment]
With the latest commit, the logs are now down to:
```
2023-02-24T14:02:22+00:00 ERR error processing HTTP request error="rpc error: code = Canceled desc = context canceled" http_endpoint="GET /v1/connectors/pipeline1:destination1/inspect" request_id=ce5da8e1-f101-40e8-9228-cacb9eb78fd4 stack=null
2023-02-24T14:02:22+00:00 INF session removed component=inspector.Inspector connector_id=pipeline1:destination1 inspector_session_id=3e63755c-4cd6-4828-bbe7-b9cd718b911c
2023-02-24T14:02:22+00:00 WRN failed writing websocket message error="websocket: close sent" component=grpcutil.webSocketProxy stack=null
```
The first one appears to come from grpc-gateway. The last one is about this message `{"code":1,"message":"context canceled","details":[]}` and it comes from gRPC (and grpc-gateway consequentially). I can think about how to get rid of it but IMHO the return isn't very big.:)

File: pkg/foundation/grpcutil/websocket.go [hunk 4]
```diff
@@ -233,13 +248,18 @@ func (p *webSocketProxy) startWebSocketWrite(ctx context.Context, messages chan
...
 			}
 
 			if err := conn.WriteMessage(websocket.TextMessage, message); err != nil {
-				p.logger.Warn(ctx).Err(err).Msg("[write] error writing websocket message")
+				// NB: if this connection has been closed by the client
+				// then that will cancel the request context, which in turn
+				// makes the request return `{"code":1,"message":"context canceled","details":[]}`.
+				// This proxy will try to write that, but will fail,
+				// because the connection has already been closed.
+				p.logger.Warn(ctx).Err(err).Msg("failed writing websocket message")
```
Comment (lovromazgon) [inline pkg/foundation/grpcutil/websocket.go:262]: Nice comment, how about we take that knowledge and use it in code to ignore that log message? 🙂
```suggestion
				if string(message) != `{"code":1,"message":"context canceled","details":[]}` {
					p.logger.Warn(ctx).Bytes("message", message).Err(err).Msg("failed writing websocket message")
				}
```

File: pkg/foundation/grpcutil/websocket.go [hunk 5]
```diff
@@ -109,9 +113,18 @@ func (p *webSocketProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+	ctx, cancelCtx := context.WithCancel(r.Context())
+	defer cancelCtx()
 	r = r.WithContext(ctx)
+	go func() {
+		// we're using ChanOut.Recv() so that the goroutine doesn't wait on
+		// the proxy to be done even when the request is done
+		_, _, err := cchan.ChanOut[struct{}](p.done).Recv(ctx)
+		if err != nil {
+			p.logger.Debug(ctx).Msgf("request context returned an error: %v", err)
+		}
```
Comment (lovromazgon) [inline pkg/foundation/grpcutil/websocket.go:125]: I think we should output the log regardless of the error and attach the error to the log message (if the error is `nil` it won't be attached). This way we will see that the connection was closed regardless of what triggered it and if there was an error we will also see it.
```suggestion
		p.logger.Debug(ctx).Err(err).Msgf("websocket connection closed")
```

To be precise, if `err` is `nil` it means the connection _will be closed_ (next line closes it), otherwise the connection was probably already closed. But I think we don't need to adjust our log message because of that, we will see this based on the attached error.

**Review by lovromazgon — APPROVED** [review]
Looking great already 👏  I added two more suggestions for you to consider 😉

File: pkg/foundation/grpcutil/websocket.go (hunk 4 above)
Comment (lovromazgon) [reply pkg/foundation/grpcutil/websocket.go:262]: Or another way to go around this would be to lower the level in that case:
```suggestion
				e := p.logger.Warn(ctx)
				if string(message) == `{"code":1,"message":"context canceled","details":[]}` {
					e = p.logger.Trace(ctx)
				}
				e.Bytes("message", message).Err(err).Msg("failed writing websocket message")
```

Comment (hariso) [reply pkg/foundation/grpcutil/websocket.go:262]: Lowering the log level makes sense to me!

File: pkg/foundation/grpcutil/websocket.go [hunk 6]
```diff
@@ -121,7 +121,7 @@ func (p *webSocketProxy) proxy(w http.ResponseWriter, r *http.Request) {
 		// the proxy to be done even when the request is done
 		_, _, err := cchan.ChanOut[struct{}](p.done).Recv(ctx)
 		if err != nil {
-			p.logger.Debug(ctx).Msgf("request context returned an error: %v", err)
+			p.logger.Debug(ctx).Err(err).Msgf("websocket connection will be closed")
 		}
```
[the remark this answers is not in the document]
Comment (hariso) [reply pkg/foundation/grpcutil/websocket.go:125]: My bad, even though I understood the same way.:)
