### PR TITLE
[UI] Plugin lookup logic

### LINKED ISSUE #644: Bug: UI requests plugin on inexistent endpoint
### Bug description

If the pipeline contains a plugin that is unknown to the UI (I assume the plugin fetches a list of plugins and stores it), the UI will try to request it on the URL `v1/plugins/[plugin-name]`. The endpoint doesn't exist.

We can either change how the UI works or provide the endpoint. Creating such an endpoint would make the plugin endpoints consistent with other entities in Conduit.

### Steps to reproduce

1. Run Conduit with `./conduit -pipelines.path ./examples/pipelines`
   * this will run the example file-to-file pipeline which contains two connectors using the plugin `builtin:file`
2. Open the UI and open the pipeline
3. See an error modal, also see an error in the logs:
   ```
   ERR error processing HTTP request error="rpc error: code = NotFound desc = Not Found" http_endpoint="GET /v1/plugins/builtin:file" request_id=1c0e9a73-15f2-4d06-ab79-dafa79e8b813 stack=null
   ```

### Version

v0.3.0-nightly.20220922 darwin/amd64

### PR DESCRIPTION
**Pull request by jmar910**
### Description
A bug came up at the end of last week that I discussed with @lovromazgon due to the changes outlined here https://github.com/ConduitIO/conduit/issues/427#issuecomment-1227396725 (see also https://github.com/ConduitIO/conduit/pull/609)

While this isn't a show stopping bug, it does limit the functionality of the UI when setting relationships between connectors and plugins using the new format.

As a nice-to-have and a temporary fix, I duplicate lookup logic outlined in the above comment/PR to allow for connectors to use the shortened names or special tags (`any`, `latest`) to match the right plugins.

Fixes #644 

BEFORE
Screen Shot 2022-09-26 at 6 36 12 PM

AFTER
Screen Shot 2022-09-26 at 6 37 14 PM

### Quick checks:

- [ ] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [ ] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [ ] I have written unit tests.
- [ ] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: ui/app/serializers/connector.js [hunk 1]
```diff
@@ -27,8 +27,86 @@ export default class ConnectorSerializer extends ApplicationSerializer {
 
   extractRelationship(modelName, value) {
     if (modelName === 'plugin' && value) {
+      const pluginNames = this.store.peekAll('plugin').mapBy('name');
```
Comment (jayjayjpg) [inline ui/app/serializers/connector.js:30]: Would it make sense to add a unit test for either the `extractRelationship` method of the serializer or an acceptance test asserting the correct display of connector labels in the UI?

This way, we could not only guard check against regressions, but also make it easier to add new rules for the labelling in the future

**Review by jayjayjpg — APPROVED** [review]
This reads great and thank you for the quick fix! :sparkles: I left one more suggestion on unit / acceptance testing, but otherwise this is already good to go!
