### PR TITLE
[arch-v2] Fix processor task handling filtered records

### LINKED ISSUE #2257: Bug: processor chain crashes after filter
### Bug description

Any processor that executes after `filter` will crash with:

```
ERR pipeline worker stopped error="task outbox-events:source:enrich_metadata: processor didn't return any records"
```

As explained by @hariso, this is because a filter record is of a special type.

### Steps to reproduce

Example pipeline:

```
version: 2.2
pipelines:
  - id: outbox-events
    status: running
    connectors:
      - id: source
        type: source
        plugin: builtin:postgres
        settings:
          url: ${PG_SOURCE_DSN}
          tables: outbox_events
          cdcMode: logrepl
          logrepl.autoCleanup: 'false'
          logrepl.publicationName: cnd_outbox
          logrepl.slotName: cnd_outbox_events
          logrepl.withAvroSchema: 'false'
          snapshot.fetchSize: '1000'
          snapshotMode: initial
        processors:
          - id: insert_only
            plugin: 'filter'
            condition: '{{ ne .Operation 1 }}'
          - id: enrich_metadata
            plugin: 'custom.javascript'
            settings:
              script: |
                function process(rec) {
                  return rec;
                }
     - id: output-log
       type: destination
       plugin: builtin:log
       settings:
         sdk.schema.extract.key.enabled: 'false'
         sdk.schema.extract.payload.enabled: 'false'
```

### Version

v0.13.4

### PR DESCRIPTION
**Pull request by lovromazgon**
### Description

This fixes the processor task handling filtered records in the v2 architecture.

~I added a `TODO` comment for the destination task that can experience a similar problem when handling batches that include filtered records. That part will be done in a separate PR to keep the changes small and easily reviewable.~

This now also includes the work from 2 other PRs:
- https://github.com/ConduitIO/conduit/pull/2279
- https://github.com/ConduitIO/conduit/pull/2287

Fixes #2257

### Quick checks

- [X] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [X] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [X] I have written unit tests.
- [X] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: pkg/lifecycle-poc/funnel/processor.go [hunk 1]
```diff
@@ -88,38 +88,42 @@ func (t *ProcessorTask) Do(ctx context.Context, b *Batch) error {
 	}
 	t.metrics.Observe(len(recsOut), start)
 
+	// Map active records back to their original indices in the batch, but only
+	// if we have filtered records. Otherwise, we can just use the original indices.
+	var activeIndices []int
+	if b.filterCount > 0 {
+		activeIndices = make([]int, 0, len(b.records))
```
Comment (raulb) [inline pkg/lifecycle-poc/funnel/processor.go:95]: Shouldn't this be the length of `b.filterCount` instead?

```suggestion
		activeIndices = make([]int, 0, len(b.filterCount))
```

Comment (raulb) [reply pkg/lifecycle-poc/funnel/processor.go:95]: Unrelated, as someone who is not very familiar with the processor code, I feel this `Do` method could benefit from a comment and/or a refactor, as I see it is kind of lengthy.

**Review by raulb — APPROVED** [review]
Code reads better now, thank you @lovromazgon
