### PR TITLE
Fix a deadlock in source connectors

### LINKED ISSUE #570: Performance: When running at 20k msg/s, progress is being made only briefly
### Bug description

In the workload where we generate 20k mgs/s, progress is being made only briefly, at the beginning of the test. After that, the test report shows no change in record count.

### Steps to reproduce

1. Run the workload here: https://github.com/ConduitIO/streaming-benchmarks/blob/haris/ec2-helpers/workloads/small-messages-20k-msg-per-sec.sh

### Version

{   "version": "v0.3.0-nightly.20220811",   "os": "linux",   "arch": "amd64" }

PS: The test report cannot be attached for some reason. I'll try to add it later.

### PR DESCRIPTION
**Pull request by hariso**
### Description

Fixes a deadlock in the source connector. Also upgrade golangci and fixes two new reported issues.

**Cause of the deadlock**:
Here's a simplified representation of how the source connector ack's records:
```
source.Ack()
    lock connector
    defer unlock connector
  
    update position in connector
    connectorPersister.Persist()
```
Here's how Persist() works:
```
Persist()
    if batch is full
        triggerFlush()

triggerFlush()
    wait for any running flusher to finish
    // trigger a flush in a separate goroutine
    go flushNow()    

flushNow()
    start new DB transaction
    serialize connector -> requires locking the connector
    persist connector state
```
If the source is acking really fast, then it's possible that, while `flushNow()` is still running (starting a new DB txn, but didn't lock the connector yet), another flush needs to be triggered. 

`Ack()` locks the connector, calls `triggerFlush()` (indirectly), which is waiting for the `flushNow()` from previous batch. `flushNow()` tries to acquire a lock, but cannot since `Ack()` is actually waiting on it to be done with the flush, to trigger a new one. 

Fixes #570.

### Quick checks:

- [ ] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [ ] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [ ] I have written unit tests.
- [ ] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: pkg/connector/source_test.go [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+		}()
+	}
+
+	if waitTimeout(&wg, 100*time.Millisecond) {
+		is.Fail() // timeout reached
+	}
+}
+
+// waitTimeout was copied from pkg/pipeline/stream/stream_test.go
+func waitTimeout(wg *sync.WaitGroup, timeout time.Duration) bool {
```
Comment (hariso) [inline pkg/connector/source_test.go:93]: I'm not too happy with this copy-paste, I'll try to come up with something better.

Comment (lovromazgon) [reply pkg/connector/source_test.go:93]: Don't bother, I'd rather we focus on finishing more important stuff before the release 😉 This can be easily done in a follow-up, besides, I'm sure we need to add these timeouts in multiple places. I'd rather do it separately by adding a utility like we [wanted to do in the SDK](https://github.com/ConduitIO/conduit-connector-sdk/commit/a9290b473be448836a4a0225afffa1215eda8307) and make sure we have timeouts wherever we need them, not only in these two tests.

**Review by lovromazgon — APPROVED** [review]
Great work 🚀

File: pkg/connector/source_test.go (hunk 1 above)
Comment (hariso) [reply pkg/connector/source_test.go:93]: Agreed. :+1:
